---
params:
  uaadb_user: (( vault meta.vault "/uaadb:user" ))
  uaadb_password: (( vault meta.vault "/uaadb:password" ))
  uaadb_scheme: mysql
  uaadb_port: 3306

  ccdb_user: (( vault meta.vault "/ccdb:user" ))
  ccdb_password: (( vault meta.vault "/ccdb:password" ))
  ccdb_scheme: mysql
  ccdb_port: 3306

  diegodb_user: (( vault meta.vault "/diegodb:user" ))
  diegodb_password: (( vault meta.vault "/diegodb:password" ))
  diegodb_scheme: mysql
  diegodb_port: 3306

  routingdb_user: (( vault meta.vault "/routingdb:user" ))
  routingdb_password: (( vault meta.vault "/routingdb:password" ))
  routingdb_scheme: mysql
  routingdb_port: 3306

  netpoldb_user: (( vault meta.vault "/netpoldb:user" ))
  netpoldb_password: (( vault meta.vault "/netpoldb:password" ))
  netpoldb_scheme: mysql
  netpoldb_port: 3306

  silkdb_user: (( vault meta.vault "/silkdb:user" ))
  silkdb_password: (( vault meta.vault "/silkdb:password" ))
  silkdb_scheme: mysql
  silkdb_port: 3306
