---
params:
  uaadb_host: (( grab instance_groups.postgres.networks[0].static_ips[0] ))
  uaadb_user: uaaadmin
  uaadb_password: (( vault meta.vault "/uaadb:password" ))
  uaadb_scheme: postgresql
  uaadb_port: 5432

  ccdb_host: (( grab instance_groups.postgres.networks[0].static_ips[0] ))
  ccdb_user: ccadmin
  ccdb_password: (( vault meta.vault "/ccdb:password" ))
  ccdb_scheme: postgres
  ccdb_port: 5432

  diegodb_host: (( grab instance_groups.postgres.networks[0].static_ips[0] ))
  diegodb_user: diegoadmin
  diegodb_password: (( vault meta.vault "/diegodb:password" ))
  diegodb_scheme: postgres
  diegodb_port: 5432

  routingdb_host: (( grab instance_groups.postgres.networks[0].static_ips[0] ))
  routingdb_user: routingadmin
  routingdb_password: (( vault meta.vault "/routingdb:password" ))
  routingdb_scheme: postgres
  routingdb_port: 5432

  netpoldb_host: (( grab instance_groups.postgres.networks[0].static_ips[0] ))
  netpoldb_user: netpoladmin
  netpoldb_password: (( vault meta.vault "/netpoldb:password" ))
  netpoldb_scheme: postgres
  netpoldb_port: 5432

  silkdb_host: (( grab instance_groups.postgres.networks[0].static_ips[0] ))
  silkdb_user: silkadmin
  silkdb_password: (( vault meta.vault "/silkdb:password" ))
  silkdb_scheme: postgres
  silkdb_port: 5432
